# Generated by Django 6.0.3 on 2026-04-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeE', models.CharField(max_length=100)),
                ('paísE', models.CharField(max_length=100)),
                ('vitorias', models.IntegerField()),
                ('best_time', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bestP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeP', models.CharField(max_length=100)),
                ('paísP', models.CharField(max_length=100)),
                ('vencedores', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bestT', models.DecimalField(decimal_places=2, max_digits=3)),
                ('campeao', models.IntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipe')),
            ],
        ),
    ]
