# Generated by Django 4.1.3 on 2026-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('vitorias', models.IntegerField(default=0)),
                ('menor_tempo', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeE', models.CharField(max_length=100)),
                ('paisE', models.CharField(max_length=100)),
                ('vitorias', models.IntegerField(default=0)),
                ('best_time', models.CharField(blank=True, max_length=100, null=True)),
                ('bestP', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilotoNome', models.CharField(max_length=100)),
                ('pilotoEquipe', models.CharField(max_length=100)),
                ('pilotoDataNasc', models.DateField(blank=True, null=True)),
                ('pilotoNumeracao', models.IntegerField(blank=True, null=True)),
                ('pilotoPais', models.CharField(blank=True, max_length=100, null=True)),
                ('pilotoFoto', models.ImageField(blank=True, null=True, upload_to='systemDrivers')),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeP', models.CharField(max_length=100)),
                ('paísP', models.CharField(max_length=100)),
                ('vencedores', models.CharField(max_length=100)),
            ],
        ),
    ]
