# Generated by Django 6.0.3 on 2026-04-07 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('vitorias', models.IntegerField(default=0)),
                ('menor_tempo', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeE', models.CharField(max_length=100)),
                ('paisE', models.CharField(max_length=100)),
                ('vitorias', models.IntegerField(default=0)),
                ('best_time', models.CharField(blank=True, max_length=100, null=True)),
                ('bestP', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeP', models.CharField(max_length=100)),
                ('paísP', models.CharField(max_length=100)),
                ('vencedores', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('paisPiloto', models.CharField(max_length=100)),
                ('bestT', models.DecimalField(decimal_places=3, max_digits=5)),
                ('campeao', models.IntegerField(default=0)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipe')),
            ],
        ),
    ]
